In [2]:
#1
import numpy as np

In [3]:
arr1 = np.array([1,2,3,4,5,6],dtype='float')
print('Single dimension')
print(arr1)
arr2 = np.array([[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14],[15,16,17,18,19],[20,21,22,23,24]],dtype='str')
print('\n Two dimension')
print(arr2)

Single dimension
[1. 2. 3. 4. 5. 6.]

 Two dimension
[['1' '2' '3' '4' '5']
 ['5' '6' '7' '8' '9']
 ['10' '11' '12' '13' '14']
 ['15' '16' '17' '18' '19']
 ['20' '21' '22' '23' '24']]


In [4]:
#2
print('Display the  Datatype & dimension arr1: ',arr1.dtype,arr1.shape)
print('\nDisplay the  Datatype & dimension arr2: ',arr2.dtype,arr2.shape)

Display the  Datatype & dimension arr1:  float64 (6,)

Display the  Datatype & dimension arr2:  <U2 (5, 5)


In [5]:
a = arr1.reshape(3,2)
print('Display the reshap(3,2) and 2-d')
print(a)
b = arr2.reshape(-1)   
print('\n Display the reshap(-1) and 1-d')
print(b)

Display the reshap(3,2) and 2-d
[[1. 2.]
 [3. 4.]
 [5. 6.]]

 Display the reshap(-1) and 1-d
['1' '2' '3' '4' '5' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24']


In [6]:
#3
arr3 = np.zeros([3,4])
print('This is a zero initialized value (3,4): ')
print(arr3)
arr4 = np.ones([6],dtype = 'int')
print('\nThis is one initialized value (6) and int: ')
print(arr4)

This is a zero initialized value (3,4): 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

This is one initialized value (6) and int: 
[1 1 1 1 1 1]


In [7]:
#4
list1 = [10,20,30,40,50]
arr5 = np.asarray(list1,dtype = 'float')
print('This is list function convert float')
print(arr5)
arr6 = np.fromiter(list1,dtype = 'int')
print('\nThis is list function convert int in use fromiter')
print(arr6)

This is list function convert float
[10. 20. 30. 40. 50.]

This is list function convert int in use fromiter
[10 20 30 40 50]


In [8]:
#5
arr7 = np.arange(12,99,3)
print(' Display arange menthod ')
print(arr7)
arr8 = np.linspace(12,99,50)
print('\n Display linspace menthod ')
print(arr8)

 Display arange menthod 
[12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72 75 78 81
 84 87 90 93 96]

 Display linspace menthod 
[12.         13.7755102  15.55102041 17.32653061 19.10204082 20.87755102
 22.65306122 24.42857143 26.20408163 27.97959184 29.75510204 31.53061224
 33.30612245 35.08163265 36.85714286 38.63265306 40.40816327 42.18367347
 43.95918367 45.73469388 47.51020408 49.28571429 51.06122449 52.83673469
 54.6122449  56.3877551  58.16326531 59.93877551 61.71428571 63.48979592
 65.26530612 67.04081633 68.81632653 70.59183673 72.36734694 74.14285714
 75.91836735 77.69387755 79.46938776 81.24489796 83.02040816 84.79591837
 86.57142857 88.34693878 90.12244898 91.89795918 93.67346939 95.44897959
 97.2244898  99.        ]


In [9]:
#6
print(arr2)
print('\n')
print(arr2[0:1])
print('\n')
print(arr2[1][3])
print('\n')
print (arr2[1])

[['1' '2' '3' '4' '5']
 ['5' '6' '7' '8' '9']
 ['10' '11' '12' '13' '14']
 ['15' '16' '17' '18' '19']
 ['20' '21' '22' '23' '24']]


[['1' '2' '3' '4' '5']]


8


['5' '6' '7' '8' '9']


In [10]:
#7
arr9 = np.array([[101, 322, 768], [233, 124, 390], [534, 122, 216]])
print('This is a 2-dimensional array')
print(arr9)
print('\n Display the integer index value')
arr10 = arr9[[0,0,1,2],[0,1,2,1]]
print(arr10)
print('\n Display the slicing operations ')
arr11 = arr9[1:]
print(arr11)

This is a 2-dimensional array
[[101 322 768]
 [233 124 390]
 [534 122 216]]

 Display the integer index value
[101 322 390 122]

 Display the slicing operations 
[[233 124 390]
 [534 122 216]]


In [11]:
#8
print(arr9)
print('\n Display the boolean method in greater than 200')
print(arr9[arr9 > 200])
print('\n Display the boolean method in non-nan element ')
print(arr9[~np.isnan(arr9)])
print('\n Display the boolean method in all non-float value')
print(arr9[arr9.dtype!='float'])
print('\n This is a broadcasting ')
c = np.array([1,2,3])
print(arr9 + c)

[[101 322 768]
 [233 124 390]
 [534 122 216]]

 Display the boolean method in greater than 200
[322 768 233 390 534 216]

 Display the boolean method in non-nan element 
[101 322 768 233 124 390 534 122 216]

 Display the boolean method in all non-float value
[[[101 322 768]
  [233 124 390]
  [534 122 216]]]

 This is a broadcasting 
[[102 324 771]
 [234 126 393]
 [535 124 219]]


In [12]:
#9
print('\n Display the Transpose arr9')
print(arr9.T)
print('\n Display the concatenate function ')
print(np.concatenate((arr1,arr4)))


 Display the Transpose arr9
[[101 233 534]
 [322 124 122]
 [768 390 216]]

 Display the concatenate function 
[1. 2. 3. 4. 5. 6. 1. 1. 1. 1. 1. 1.]


In [15]:
#10
print(arr2)
print('\n Display the horizontal stack')
print(np.hstack(arr2))
print('\n Display the vertical stack')
print(np.vstack(arr2))
print('\n Display the horizontal split ')
print(np.hsplit(arr2))
print('\n Display the vertical split')
print(np.vsplit(arr2))

[['1' '2' '3' '4' '5']
 ['5' '6' '7' '8' '9']
 ['10' '11' '12' '13' '14']
 ['15' '16' '17' '18' '19']
 ['20' '21' '22' '23' '24']]

 Display the horizontal stack
['1' '2' '3' '4' '5' '5' '6' '7' '8' '9' '10' '11' '12' '13' '14' '15'
 '16' '17' '18' '19' '20' '21' '22' '23' '24']

 Display the vertical stack
[['1' '2' '3' '4' '5']
 ['5' '6' '7' '8' '9']
 ['10' '11' '12' '13' '14']
 ['15' '16' '17' '18' '19']
 ['20' '21' '22' '23' '24']]

 Display the horizontal split 


TypeError: _hvdsplit_dispatcher() missing 1 required positional argument: 'indices_or_sections'

In [ ]:
import numpy as np



In [ ]:
a = np.array([1,2,3,4,5,6],dtype = 'float')
print(a)
print(a.reshape(3,2))